- name: Provision and configure servers
  hosts: localhost
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure the server is up-to-date
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Nginx
      apt:
        name: "{{nginx_package}}"
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Use custom configuration
      copy:
        src: files/{{custom_config_file}}
        dest: /etc/nginx/conf.d/{{custom_config.file}}
        owner: root
        group: root
        mode: '0644'

    - name: Ensure the firewall allows HTTP traffic
      ufw:
        rule: allow
        name: 'Nginx HTTP'
        state: enabled

    - name: Restart Nginx to apply configuration changes
      systemd:
        name: nginx
        state: restarted
    
