- name: Provision and configure servers
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure the server is up-to-date
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure the firewall allows HTTP traffic
      ufw:
        rule: allow
        name: 'Nginx HTTP'
        state: enabled

    - name: Restart Nginx to apply configuration changes
      systemd:
        name: nginx
        state: restarted
    
